"""refactor_nonnullable_doctor_time

Revision ID: 1a465f5a6b2f
Revises: cafc80cee16f
Create Date: 2026-03-16 11:02:55.423110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a465f5a6b2f'
down_revision: Union[str, Sequence[str], None] = 'cafc80cee16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('doctors', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('doctors', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###
