"""accepting nullable user_id in doctor and patient

Revision ID: 5e65ca416117
Revises: 43c101bfd223
Create Date: 2026-03-20 17:00:25.556524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e65ca416117'
down_revision: Union[str, Sequence[str], None] = '43c101bfd223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'DOCTOR', 'PATIENT', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'DOCTOR', 'PATIENT', name='userrole'),
               nullable=True)
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'user_id')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'user_id')
    # ### end Alembic commands ###
