"""not_accept_nullable_user_id

Revision ID: 9bb87ba6e509
Revises: 5e65ca416117
Create Date: 2026-03-21 14:08:42.444825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9bb87ba6e509'
down_revision: Union[str, Sequence[str], None] = '5e65ca416117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('patients', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('doctors', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
