"""add is_active to appointments

Revision ID: c67d44c3ce69
Revises: 1a465f5a6b2f
Create Date: 2026-03-17 08:38:50.392502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c67d44c3ce69'
down_revision: Union[str, Sequence[str], None] = '1a465f5a6b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'is_active')
    # ### end Alembic commands ###
