"""Initial_postgres_migration

Revision ID: cafc80cee16f
Revises: 
Create Date: 2026-03-16 10:18:07.550540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cafc80cee16f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('doctors', sa.Column('end_time', sa.Time(), nullable=True))
    op.create_index(op.f('ix_doctors_end_time'), 'doctors', ['end_time'], unique=False)
    op.create_index(op.f('ix_doctors_start_time'), 'doctors', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_start_time'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_end_time'), table_name='doctors')
    op.drop_column('doctors', 'end_time')
    op.drop_column('doctors', 'start_time')
    # ### end Alembic commands ###
